# Railway configuration (minimal) for SmartDocs AI backend
# Targets backend/ subdirectory Dockerfile in monorepo

[build]
dockerfilePath = "backend/Dockerfile"
context = "backend"
target = "production"  # ensure production stage (avoids dev fastapi server)

[deploy]
# Use Dockerfile CMD (uvicorn); minimal restart policy
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
rootDirectory = "backend"